
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:206 (message)"
      - "C:/Users/joedo/zephyrproject/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "C:/Users/joedo/zephyrproject/zephyr/cmake/modules/zephyr_default.cmake:138 (include)"
      - "C:/Users/joedo/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "C:/Users/joedo/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:7 (find_package)"
    message: |
      The target system is: Generic - 3.5.99 - arm
      The host system is: Windows - 10.0.22621 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "C:/Users/joedo/zephyrproject/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "C:/Users/joedo/zephyrproject/zephyr/cmake/modules/zephyr_default.cmake:138 (include)"
      - "C:/Users/joedo/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "C:/Users/joedo/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:7 (find_package)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: C:/Users/joedo/zephyr-sdk-0.16.3/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      c:/users/joedo/zephyr-sdk-0.16.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: c:/users/joedo/zephyr-sdk-0.16.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/lib\\libc.a(lib_a-exit.o): in function `exit':
      exit.c:(.text.exit+0x34): undefined reference to `_exit'
      collect2.exe: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "C:/Users/joedo/zephyrproject/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "C:/Users/joedo/zephyrproject/zephyr/cmake/modules/zephyr_default.cmake:138 (include)"
      - "C:/Users/joedo/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "C:/Users/joedo/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:7 (find_package)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Users/joedo/zephyr-sdk-0.16.3/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc.exe 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is GNU, found in:
        C:/Users/joedo/zephyrproject/cansw_processor/twister-out/processor/samples/subsys/rtio/sensor_batch_processing/sample.rtio.sensor_batch_processing/CMakeFiles/3.27.6/CompilerIdC/CMakeCCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "C:/Users/joedo/zephyrproject/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "C:/Users/joedo/zephyrproject/zephyr/cmake/modules/zephyr_default.cmake:138 (include)"
      - "C:/Users/joedo/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "C:/Users/joedo/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:7 (find_package)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: C:/Users/joedo/zephyr-sdk-0.16.3/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      c:/users/joedo/zephyr-sdk-0.16.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: c:/users/joedo/zephyr-sdk-0.16.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/lib\\libc.a(lib_a-exit.o): in function `exit':
      exit.c:(.text.exit+0x34): undefined reference to `_exit'
      collect2.exe: error: ld returned 1 exit status
      
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "C:/Users/joedo/zephyrproject/zephyr/cmake/modules/kernel.cmake:128 (project)"
      - "C:/Users/joedo/zephyrproject/zephyr/cmake/modules/zephyr_default.cmake:138 (include)"
      - "C:/Users/joedo/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "C:/Users/joedo/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:7 (find_package)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Users/joedo/zephyr-sdk-0.16.3/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc.exe 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.o"
      
      The CXX compiler identification is GNU, found in:
        C:/Users/joedo/zephyrproject/cansw_processor/twister-out/processor/samples/subsys/rtio/sensor_batch_processing/sample.rtio.sensor_batch_processing/CMakeFiles/3.27.6/CompilerIdCXX/CMakeCXXCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:1104 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineASMCompiler.cmake:127 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "C:/Users/joedo/zephyrproject/zephyr/cmake/modules/kernel.cmake:134 (enable_language)"
      - "C:/Users/joedo/zephyrproject/zephyr/cmake/modules/zephyr_default.cmake:138 (include)"
      - "C:/Users/joedo/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)"
      - "C:/Users/joedo/zephyrproject/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)"
      - "CMakeLists.txt:7 (find_package)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" matched "(GNU assembler)|(GCC)|(Free Software Foundation)":
      arm-zephyr-eabi-gcc.exe (Zephyr SDK 0.16.3) 12.2.0
      Copyright (C) 2022 Free Software Foundation, Inc.
      This is free software; see the source for copying conditions.  There is NO
      warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/Internal/CheckSourceCompiles.cmake:101 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/Internal/CheckCompilerFlag.cmake:18 (cmake_check_source_compiles)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CheckCCompilerFlag.cmake:51 (cmake_check_compiler_flag)"
      - "C:/Users/joedo/zephyrproject/zephyr/cmake/modules/extensions.cmake:2003 (check_c_compiler_flag)"
      - "C:/Users/joedo/zephyrproject/zephyr/cmake/modules/extensions.cmake:1095 (check_compiler_flag)"
      - "C:/Users/joedo/zephyrproject/zephyr/cmake/modules/extensions.cmake:2042 (zephyr_check_compiler_flag)"
      - "C:/Users/joedo/zephyrproject/zephyr/cmake/modules/extensions.cmake:2018 (target_cc_option_fallback)"
      - "C:/Users/joedo/zephyrproject/zephyr/cmake/modules/extensions.cmake:122 (target_cc_option)"
      - "C:/Users/joedo/zephyrproject/zephyr/CMakeLists.txt:453 (zephyr_cc_option)"
    directories:
      source: "C:/Users/joedo/zephyrproject/cansw_processor/twister-out/processor/samples/subsys/rtio/sensor_batch_processing/sample.rtio.sensor_batch_processing/CMakeFiles/CMakeScratch/TryCompile-jxmff5"
      binary: "C:/Users/joedo/zephyrproject/cansw_processor/twister-out/processor/samples/subsys/rtio/sensor_batch_processing/sample.rtio.sensor_batch_processing/CMakeFiles/CMakeScratch/TryCompile-jxmff5"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
      CMAKE_MODULE_PATH: "C:/Users/joedo/zephyrproject/zephyr/cmake/modules"
    buildResult:
      variable: "check_fmacro_prefix_map_C__Users_joedo_zephyrproject_zephyr_samples_subsys_rtio_sensor_batch_processing_CMAKE_SOURCE_DIR_C__nostartfiles__nostdlib__isystem__c__users_joedo_zephyr_sdk_0_16_3_arm_zephyr_eabi_bin____lib_gcc_arm_zephyr_eabi_12_2_0_include___isystem__c__users_joedo_zephyr_sdk_0_16_3_arm_zephyr_eabi_bin____lib_gcc_arm_zephyr_eabi_12_2_0_include_fixed___Wl___unresolved_symbols_ignore_in_object_files__Wl___entry_0"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/joedo/zephyrproject/cansw_processor/twister-out/processor/samples/subsys/rtio/sensor_batch_processing/sample.rtio.sensor_batch_processing/CMakeFiles/CMakeScratch/TryCompile-jxmff5'
        
        Run Build Command(s): C:/ProgramData/chocolatey/bin/ninja.exe -v cmTC_5ee0e
        [1/2] C:\\Users\\joedo\\zephyr-sdk-0.16.3\\arm-zephyr-eabi\\bin\\arm-zephyr-eabi-gcc.exe -Dcheck_fmacro_prefix_map_C__Users_joedo_zephyrproject_zephyr_samples_subsys_rtio_sensor_batch_processing_CMAKE_SOURCE_DIR_C__nostartfiles__nostdlib__isystem__c__users_joedo_zephyr_sdk_0_16_3_arm_zephyr_eabi_bin____lib_gcc_arm_zephyr_eabi_12_2_0_include___isystem__c__users_joedo_zephyr_sdk_0_16_3_arm_zephyr_eabi_bin____lib_gcc_arm_zephyr_eabi_12_2_0_include_fixed___Wl___unresolved_symbols_ignore_in_object_files__Wl___entry_0  -nostartfiles -nostdlib -isystem "c:/users/joedo/zephyr-sdk-0.16.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/include" -isystem "c:/users/joedo/zephyr-sdk-0.16.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/include-fixed" -Wl,--unresolved-symbols=ignore-in-object-files -Wl,--entry=0   -fmacro-prefix-map=C:/Users/joedo/zephyrproject/zephyr/samples/subsys/rtio/sensor_batch_processing=CMAKE_SOURCE_DIR -o CMakeFiles/cmTC_5ee0e.dir/src.c.obj -c C:/Users/joedo/zephyrproject/cansw_processor/twister-out/processor/samples/subsys/rtio/sensor_batch_processing/sample.rtio.sensor_batch_processing/CMakeFiles/CMakeScratch/TryCompile-jxmff5/src.c
        [2/2] cmd.exe /C "cd . && C:\\Users\\joedo\\zephyr-sdk-0.16.3\\arm-zephyr-eabi\\bin\\arm-zephyr-eabi-gcc.exe -nostartfiles -nostdlib -isystem "c:/users/joedo/zephyr-sdk-0.16.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/include" -isystem "c:/users/joedo/zephyr-sdk-0.16.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/include-fixed" -Wl,--unresolved-symbols=ignore-in-object-files -Wl,--entry=0  CMakeFiles/cmTC_5ee0e.dir/src.c.obj -o cmTC_5ee0e   && cd ."
        
      exitCode: 0
...
